canary-checker/docs/reference/http.mdx, canary-checker/docs/scripting/gotemplate.md
resolves: https://github.com/flanksource/docs/issues/126
=> docs: templating URL and body in HTTP check

mission-control/docs/playbooks/concepts/playbook.md, mission-control/docs/playbooks/examples/action-filter.md, mission-control/docs/playbooks/examples/exec-delay.md, mission-control/docs/playbooks/triggers/events.md, mission-control/sidebars.js
resolves: https://github.com/flanksource/docs/issues/123
=> Playbooks new features

canary-checker/docs/reference/alert-manager.mdx
=> chore: add namespace to alertmanager transform result

mission-control/docs/config-db/scrapers/kubernetes.md
Closes: https://github.com/flanksource/docs/issues/124
=> feat: add docs for configdb k8s relationships

mission-control/docs/config-db/concepts/transform.md
resolves: https://github.com/flanksource/docs/issues/122
=> docs: catalog event exclusion

.prettierrc, canary-checker/docs/scripting/cel.md
resolves: https://github.com/flanksource/docs/issues/148
=> feat: cel macro documentation

canary-checker/docs/reference/resource_selector.md, mission-control/Makefile, mission-control/docs/topology/concepts/linking-components.md, mission-control/docs/topology/references/components.md, mission-control/sidebars.js
Fixes: https://github.com/flanksource/docs/issues/131
=> chore: update resource selector documentation

canary-checker/docs/windows.md, canary-checker/sidebars.js
Added help doc and 'Windows' Installation option
=> Documentation for usage of Windows install-service.ps1 

common/src/css/custom.css, mission-control/docusaurus.config.js
=> feat: update code block theming

canary-checker/docusaurus.config.js, canary-checker/package-lock.json, canary-checker/package.json, mission-control/docs/registry/aws.mdx, mission-control/docs/registry/azure.md
Fixes: https://github.com/flanksource/mission-control-registry/issues/158
=> chore: remove connectiondetails prefix in aws/azure

common/src/components/Fields.jsx, mission-control/docs/config-db/scrapers/kubernetes.md, mission-control/docs/reference/types.md
resolves: https://github.com/flanksource/docs/issues/228
=> doc(config-db): custom annotations

mission-control/docs/config-db/concepts/health_status.md, mission-control/docs/playbooks/Actions/gitops.mdx, mission-control/docs/playbooks/webhooks.md, mission-control/docs/reference/connections/index.md, mission-control/docs/reference/playbooks/env-vars.md
related to: https://github.com/flanksource/docs/issues/230
=> connection string ref & playbook env vars & webhook template var

.gitmodules, canary-checker/docs/reference/1-webhook.mdx, mission-control/docs/installation/artifacts.md
resolves: https://github.com/flanksource/docs/issues/243
=> chore: update docs for webhook check

common/src/components/Scraper.jsx, mission-control/docs/config-db/scrapers/kubernetes.mdx
resolves: https://github.com/flanksource/docs/issues/239
=> Kubernetes docs update

mission-control/docs/notifications/events/components.md, mission-control/docs/notifications/events/configs.md, mission-control/docs/notifications/events/health-checks.md, mission-control/docs/notifications/examples/index.md
Fixes: https://github.com/flanksource/docs/issues/251
=> chore: update notification examples for each type

mission-control/docs/notifications/examples/kube-job-failing.md, mission-control/docs/notifications/examples/kube-podcrashlooping.md, mission-control/docs/notifications/examples/kube-unhealthy-deployment.md
Fixes: https://github.com/flanksource/docs/issues/269
Depends on: https://github.com/flanksource/mission-control/pull/1348
=> chore: move notification examples to mission-control/fixutres

mission-control/docs/installation/_properties.mdx, mission-control/docs/installation/_properties_identity_mapper.mdx, mission-control/docs/installation/self-hosted/oidc.mdx, mission-control/docs/reference/helm/mission-control.mdx, mission-control/docs/reference/index.mdx, mission-control/docs/reference/rbac.mdx
resolves: https://github.com/flanksource/docs/issues/264
=> docs: identity mapper

canary-checker/docs/scripting/index.mdx
Reverts flanksource/docs#299
Not sure why the build fails, `docusaurus start` works but `docusaurus build` fails with error
```
[ERROR] Error: Unable to build website for locale en.
at tryToBuildLocale (/home/yash/Work/docs/mission-control/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
at async /home/yash/Work/docs/mission-control/node_modules/@docusaurus/core/lib/commands/build.js:65:9
at async mapAsyncSequential (/home/yash/Work/docs/mission-control/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
at async Command.build (/home/yash/Work/docs/mission-control/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
[cause]: Error: Docusaurus static site generation failed for 1 paths:
- "/canary-checker/scripting/"
at generateStaticFiles …
```
=> Revert "chore: add index list in scripting docs"

.github/workflows/style.yml, common/src/components/Action.jsx, common/src/components/Fields.jsx, mission-control/docs/guide/playbooks/actions/ai.mdx, mission-control/docs/reference/connections/anthropic.mdx, mission-control/docs/reference/connections/ollama.mdx, mission-control/docs/reference/connections/openai.mdx, mission-control/package-lock.json, mission-control/package.json
resolves: https://github.com/flanksource/docs/issues/319
=> docs: ai playbook action

common/src/components/Fields.jsx, mission-control/docs/reference/connections/kubernetes.mdx
resolves: https://github.com/flanksource/docs/issues/342
=> docs: Kubernetes connection ref

mission-control/docs/guide/config-db/concepts/plugins.mdx
resolves: https://github.com/flanksource/docs/issues/344
=> feat: scrapePlugins

mission-control/docs/guide/notifications/concepts/inhibitions.mdx, mission-control/docs/reference/notifications/_notification.mdx
resolves: https://github.com/flanksource/docs/issues/355
=> notification inhibitions

mission-control/docs/guide/topology/concepts/properties.mdx
Fixes: https://github.com/flanksource/docs/issues/336
=> chore: add topology property docs

canary-checker/docusaurus.config.js, mission-control/docusaurus.config.ts
Fixes: https://github.com/flanksource/docs/issues/352
=> chore: add demo links

mission-control/docs/guide/permissions/index.mdx
resolves: https://github.com/flanksource/docs/issues/368
=> feat: update permission docs

mission-control/docs/guide/notifications/index.mdx, mission-control/docs/guide/playbooks/index.mdx, mission-control/docs/reference/connections/index.mdx
resolves: https://github.com/flanksource/docs/issues/371
=> docs: permissions for playbooks/connections/notification

.editorconfig, common/src/components/Helm.jsx, mission-control/docs/installation/_aws_iam.mdx, mission-control/docs/installation/_gke_iam.mdx, mission-control/docs/installation/saas/gke.mdx, mission-control/docs/installation/self-hosted/gke.mdx, mission-control/sidebars.js
Fixes: https://github.com/flanksource/docs/issues/372
=> feat: gke installation

canary-checker/docs/reference/1-catalog.mdx, canary-checker/docs/reference/1-kubernetes.mdx, common/snippets/_resource-selector.mdx, mission-control/docs/reference/resource-selector.md
=> chore: update resource selector references and add examples
